### PR TITLE
[WIP] VCF parser improvements

### PR DESCRIPTION
**Pull request by valeriuo**
1. `vcf_parse` was split into dedicated parsing methods `vcf_parse_filter`, `vcf_parse_info`, along the already present `vcf_parse_format`.
2. Some calls to `strtol` have been replaced with `hts_str2int`.
3. Calls to `strtod` have been replaced with `hts_str2dbl` (by @jkbonfield).

A 2% speed improvement has been observed on a 1812841 record Human genome VCF file with 2500 samples.

Still to do:

Implement other speed gains.

### CODE REVIEW

**Comment by daviesrob** [comment]
I'm getting better improvements with this.  For example, my copy of `ALL.chr22_GRCh38.genotypes.20170504.vcf.gz` (which I think came from ftp://ftp.ebi.ac.uk/1000g/ftp/release/20130502/supporting/GRCh38_positions/) and is mainly GT fields gives these perf results:

Current develop (2e36fa6):
```
    228519.040486 task-clock                #    0.990 CPUs utilized
            20,070 context-switches          #    0.000 M/sec
                25 CPU-migrations            #    0.000 M/sec
             1,084 page-faults               #    0.000 M/sec
   678,224,294,392 cycles                    #    2.968 GHz                      [83.33%]
    95,212,920,592 stalled-cycles-frontend   #   14.04% frontend cycles idle     [83.33%]
    41,060,593,139 stalled-cycles-backend    #    6.05% backend  cycles idle     [66.68%]
 1,691,261,204,308 instructions              #    2.49  insns per cycle
                                             #    0.06  stalled cycles per insn  [83.34%]
   423,121,155,198 branches                  # 1851.579 M/sec                    [83.32%]
       351,814,725 branch-misses             #    0.08% of all branches          [83.34%]

     230.841006038 seconds time elapsed

```

This PR (e7bdd84):
```
     160314.113817 task-clock                #    0.991 CPUs utilized
            13,985 context-switches          #    0.000 M/sec
                52 CPU-migrations            #    0.000 M/sec
             1,085 page-faults               #    0.000 M/sec
   467,506,712,464 cycles                    #    2.916 GHz                     [83.35%]
    97,059,528,826 stalled-cycles-frontend   #   20.76% frontend cycles idle    [83.32%]
    42,132,162,609 stalled-cycles-backend    #    9.01% backend  cycles idle    [66.68%]
 1,108,116,744,733 instructions              #    2.37  insns per cycle
                                             #    0.09  stalled cycles per insn [83.35%]
   274,548,984,846 branches                  # 1712.569 M/sec                   [83.32%]
       336,455,201 branch-misses             #    0.12% of all branches         [83.32%]

     161.809559486 seconds time elapsed

```

So at least for some files it's quite a bit better already, and I think there's plenty more could be done.

**Comment by daviesrob** [comment]
5a91631 gives a bit more speed-up:
```
     143379.702477 task-clock                #    0.986 CPUs utilized
            12,678 context-switches          #    0.000 M/sec
                29 CPU-migrations            #    0.000 M/sec
             1,084 page-faults               #    0.000 M/sec
   417,473,668,436 cycles                    #    2.912 GHz                     [83.35%]
    69,385,184,393 stalled-cycles-frontend   #   16.62% frontend cycles idle    [83.33%]
    31,097,343,902 stalled-cycles-backend    #    7.45% backend  cycles idle    [66.68%]
 1,079,187,991,406 instructions              #    2.59  insns per cycle
                                             #    0.06  stalled cycles per insn [83.35%]
   243,884,378,365 branches                  # 1700.969 M/sec                   [83.32%]
       192,217,116 branch-misses             #    0.08% of all branches         [83.32%]

     145.468588482 seconds time elapsed
```

It should be possible to make similar improvements elsewhere (i.e. pull the code to catch bad values out of the main loop). It would also be good to pull more of the code for fixing missing header lines into separate functions like the `fix_chromosome()` one in e7bdd84.

Another improvement that would make this easier to maintain would be to lengthen some of the one-letter variable names in functions like `vcf_parse_format()` as they're really hard to search for when trying to see how the function works.

**Comment by pd3** [comment]
The commit f6695d4 gives 26% speed improvement on a 7.7GB VCF with 929 samples and rich collection of FORMAT fields GT:AD:DP:GQ:PGT:PID:PL

```
$ wget -O test.vcf.gz ftp://ngs.sanger.ac.uk/production/hgdp/hgdp_wgs.20190516/hgdp_wgs.20190516.full.chr20.vcf.gz

# develop
$ perf stat ./test/test_view-2e36fa6 -B test.vcf.gz
     636273.303880      task-clock:u (msec)       #    1.000 CPUs utilized
                 0      context-switches:u        #    0.000 K/sec
                 0      cpu-migrations:u          #    0.000 K/sec
             1,178      page-faults:u             #    0.002 K/sec
 2,011,220,475,528      cycles:u                  #    3.161 GHz
 5,629,531,078,688      instructions:u            #    2.80  insn per cycle
 1,412,752,168,568      branches:u                # 2220.354 M/sec
    11,490,627,284      branch-misses:u           #    0.81% of all branches

     636.306396254 seconds time elapsed

# valeriuo-vcf_parser
$ perf stat ./test/test_view-f6695d4 -B test.vcf.gz
     470074.132946      task-clock:u (msec)       #    1.000 CPUs utilized
                 0      context-switches:u        #    0.000 K/sec
                 0      cpu-migrations:u          #    0.000 K/sec
             1,182      page-faults:u             #    0.003 K/sec
 1,483,041,135,016      cycles:u                  #    3.155 GHz
 3,991,488,922,260      instructions:u            #    2.69  insn per cycle
   926,815,005,426      branches:u                # 1971.636 M/sec
    11,172,396,247      branch-misses:u           #    1.21% of all branches

     470.196867889 seconds time elapsed
```

Also checked the integrity of the results, the output from `bcftools view` is identical.

**Comment by valeriuo** [comment]
Thanks for checking @pd3 
It might just make the cut into the next release.

**Comment by pd3** [comment]
Just finished a bigger test (32k samples) which was aimed at integrity of results. The new version produces identical results with `bcftools view`.

**Comment by daviesrob** [comment]
I've added a few improvements/bugfixes to `hts_str2dbl()`, found by fuzzing the inputs and checking that the result was binary identical to the output from `strtod()` (a binary check is needed because `nan == nan` returns false).

It found a few obscure features of `strtod()` like hex floating-point, along with a couple of bugs.  Notably leading zeros caused the decimal point to be put in the wrong place giving incorrect outputs, and `max_len` was set too high so some inputs gave rounding errors.  It was also possible to escape the `max_len` limit by putting the decimal point in exactly the right place.

The new version has so far withstood over 100 billion fuzzing attempts.

**Comment by jkbonfield** [comment]
Sorry it has a goto!  I tried getting rid of it and it harmed the optimiser.  At least gotos are self-documenting if you use a nice label. :-)

**Comment by pd3** [comment]
What can I say https://xkcd.com/292/?
:-)

But this is a good use case.

**Comment by jkbonfield** [comment]
!

I'd better keep the doors shut.

**Comment by daviesrob** [comment]
Rebased, to fix the Appveyor build.

**Comment by jkbonfield** [comment]
I did another check on 1.10 vs this PR and on a single sample (HG00096 from the above test.vcf.gz) 1.10 took 33% longer to read and with the full 2504 sample file 1.10 took 66% longer.  That's quite a significant win.  Nice team work.  :-)

**Comment by jkbonfield** [comment]
Work in progress and failing indexing checks (so not added), but I'm seeing big gains with deferred VCF FORMAT parsing.  See https://github.com/jkbonfield/htslib/commit/54f45520e37c3bb80205da695441dc3a3dea9233

Benchmark of test_view -B on a 2.5K sample file went from 7m11s to 2m42s.  A `test_view in.vcf.gz` (so printing up uncompressed VCF content) similarly sped up from 9m49 to 2m58.  Basically keeping the VCF FORMAT data in textual form until *and if* it is needed.  Once needed we convert to internal BCF form.

In theory VCF to BCF shouldn't be impacted as it's doing the text to binary conversion still, as before, however it increased from 6m48 to 7m20 (VCF.gz -> uBCF), likely due to additional mallocs and memcpys.  It's possible we can streamline some of that a bit, however it seems like a reasonable tradeoff still even as-is.

**Comment by jkbonfield** [comment]
Corrected my VCF change. See https://github.com/jkbonfield/htslib/tree/vcf_parser (not the commit hash listed above as I've updated it).

It now passes both htslib and bcftools tests, so I think I caught the right places.  This really needs an expert eye to review it though before adding it to this PR as this PR is far less contentious and more or less ready to merge.

@pd3 if you could review that last commit (https://github.com/jkbonfield/htslib/commit/d85f55331df306adad63f9fcd3d7efac5a1d759d) please in my fork I'd be grateful.  Thanks.

It could do with a couple code tidy ups (comments and maybe an error check on kputsn, but the basic gist of it is done).

**Comment by jkbonfield** [comment]
I need an adjudication on this.

Bcftools test file `test/view.vcf` ends with:

```
Y       8657215 .       C       A       999     PASS    DP4=74915,114274,1948,2\
955;DP=195469;Dels=0;FS=3.181;MQ0=0;MQ=50;PV4=0.86,1,0,1;QD=33.77;AN=2;AC=1    \
  GT:PL:DP:GQ     0:0,255:47:99   1:255,0:64:99   .
```

Bcftools (1.10) view changes that last field from `.` to `.:.:.:.`.  The new htslib makes bcftools view return `.` as it's just repeating what the input data was as it hasn't done a parse from text to binary back to text again.

That sample lacks fields.  Is that valid VCF?  If not then our test is at fault.  If it is then I guess the new behaviour is also legal.  Was this test attempting to validate that we take an incomplete field and expand it to be complete?

**Comment by pd3** [comment]
A single dot is a valid VCF and htslib expanding into `.:.:.:.` etc was just a side effect.

**Comment by jkbonfield** [comment]
Ah I see "test/view.omitgenotypes.out" test file too.  Presumably it was deliberate testing on that one to ensure to expanded.  I'll look at the other failures to validate they all come from the same origin.

**Pull request merged**
