### PR TITLE
RFC: htslib header parser

### PR DESCRIPTION
**Pull request by SamStudio8**
Following issue samtools/samtools#203 I have been experimenting with adding a BAM header parser in htslib and implementing use of its functionality in the reading in of BAM files for `samtools merge`, replacing the heavy and inefficient use of regular expressions. Currently this only handles the @RG and @PG lines, whose fields are each stored in a struct, which in turn make up a linked list stored in `bam_hdr_t`.

My C is a little rusty and I imagine my implementation could be simplified and polished somewhat, but I am happy to get some feedback on this as necessary so as I might be able to continue finishing this parser in the right direction.

See also https://github.com/samtools/samtools/pull/259

### CODE REVIEW

**Comment by SamStudio8** [comment]
Bump

**Comment by jkbonfield** [comment]
It's worth coming up with a series of requirements and evaluating the current implementations, as we have several.  Nils Homer's I think was the first (I forget where it is, probably in a pull request or his fork),  I have one in CRAM (https://github.com/samtools/htslib/blob/develop/cram/sam_header.h) and there is this.  Obviously I'm biased so I'll leave that evaluation to others. :-)

Likely some amalgamation of all of them is required.

**Comment by SamStudio8** [comment]
Presumably any such series of requirements need be defined by those steering the project so implementations can be tested empirically and *finally merged*.

**Comment by jenniferliddle** [comment]
I'm now in the position where I need to parse and edit header information.
Should I write my own functions, or use one of the existing non-canonical versions? If so, which one?
Are there any plans to integrate any of them into the main code and make an official API for doing this, or is everybody expected to write their own?

**Comment by SamStudio8** [comment]
Hi Jennifer,
I think there is a plan to integrate header parsing with an officially
supported API (potentially by samtools 1.4, but perhaps that is my own
optimism?).
I've slowly been working on my own implementation in my spare time (atop of
this previous [somewhat hacky] implementation) but I imagine that's not
particularly useful as it sounds like you are in need of this functionality
now.
I suspect John or James could provide a better run down on the currently
existing non-canon versions that you might be able to use.

If desired, I'm happy to at least try and bring this previous
implementation up to speed with the current develop branch as it is at
least the most recent (I think).

Sam

**Comment by jenniferliddle** [comment]
On 09/03/16 14:30, Sam Nicholls wrote:
> Hi Jennifer,
> I think there is a plan to integrate header parsing with an officially
> supported API (potentially by samtools 1.4, but perhaps that is my own
> optimism?).
> I've slowly been working on my own implementation in my spare time (atop of
> this previous [somewhat hacky] implementation) but I imagine that's not
> particularly useful as it sounds like you are in need of this functionality
> now.

What I've decided to do at the moment is go with James's version in 
cram, on the grounds that it is already in htslib. A minor problem with 
it is that it doesn't (yet) support deleting header items, so I'm 
currently trying to implement that. And write some unit tests :-)

**Comment by valeriuo** [comment]
Implemented as https://github.com/samtools/htslib/pull/812

**Pull request closed without merging**
