### PR TITLE
Add Google Cloud Storage support

### PR DESCRIPTION
**Pull request by jmarshall**
A reimplementation of PR #390 as separate code, now that `hopen()` provides a way to add your own HTTP headers.  (We'll eventually pull the S3 code out separately from _hfile_libcurl.c_ similarly.)

Getting the authentication token from an environment variable is a starting point that we'd like to replace with something more robust.

We also need to add the documentation from the original PR about how to create this token, but that wants to be on an upcoming webpage on http://htslib.org/doc/ rather than hidden in this source code:

> // Reformat the url for the GCS API, and add an OAuth header.
> // GCS URL format is gs://BUCKET/PATH. We convert this to
> // https://www.googleapis.com/storage/v1/b/BUCKET/o/PATH?alt=media,
> // where PATH is url-escaped.
> // We get the token for the OAuth header from the environment variable
> // GCS_OAUTH_TOKEN, which you can set using the gcloud tool, e.g.
> //  > gcloud auth application-default login
> //  > export GCS_OAUTH_TOKEN=`gcloud auth application-default print-access-token`
> // For production environments, set up a service account and use its credentials, e.g.
> //  > export GOOGLE_APPLICATION_CREDENTIALS="/path/to/key.json"
> //  > export GCS_OAUTH_TOKEN=`gcloud auth application-default print-access-token`

### CODE REVIEW

**Comment by smrgit** [comment]
thank you, this is great news -- unfortunately, I'm having trouble building htslib and samtools to test this out -- could you please help me with some build instructions?

**Comment by jkbonfield** [comment]
What exactly is it you're having problems with?

The "INSTALL" file contains the build instructions.  The GCS code isn't enabled by default as it depends on libcurl, but "./configure --enable-libcurl" should be sufficient for it to be used.  Then "make" as usual.

**Comment by jmarshall** [comment]
Building from a Git repository is a little more involved than from a release tarball.

HTSlib should be fine, using the extra instructions in [README.md](https://github.com/samtools/htslib/blob/develop/README.md) along with [INSTALL](https://github.com/samtools/htslib/blob/develop/INSTALL) and the configure option suggestions in [samtools/README](https://github.com/samtools/samtools/blob/develop/README).

Samtools similarly, but getting the m4 scripts from autoconf-archive is a mess at the moment due to samtools/samtools#500 and in particular [cf Debian bug 840974](https://bugs.debian.org/840974).  This is probably where @smrgit is running into trouble; the best way to get her past this tarpit is for us to get around to committing them to the samtools repository (sigh…).

**Comment by smrgit** [comment]
Let met know what I should try and when :-)

**Comment by jmarshall** [comment]
I've pushed the m4 script fix mentioned to samtools **develop** — see samtools/samtools@30bc5e2dbcbc13ca772a607f5a2fe1cfe12be709.

To summarise the starting-from-Git instructions across the two repositories, starting from clean current **develop** × 2 in sibling directories, use

```sh
# in …/htslib
autoheader; autoconf
cd ../samtools
autoconf -Wno-syntax
./configure --enable-plugins --enable-libcurl --with-plugin-path=$PWD/../htslib
make all plugins-htslib
```

to build a _samtools_ executable that understands `gs:` URLs.

**Comment by smrgit** [comment]
Thank you -- sorry it took me a week to get back to this.  I was able to build samtools (though I added --without-curses to the configure command), and *successfully* tested it on both an open-access and a controlled-access bam file.  I wanted to add that if you are on a Google Compute Engine VM and using a compute-engine service account, you do **not** need to run the ``gcloud auth application-default login`` step and can just go straight to
```
export GCS_OAUTH_TOKEN=`gcloud auth application-default print-access-token`
```
Here is one of the tests I ran (this bam file should be publicly accessible):
```
$ ./samtools view gs://isb-cgc-open/ccle/LUSC/DNA-Seq/C836.NCI-H1339.2.bam 7:140453130-140453140 | head | cut -c-300
D0N3RACXX120302:5:1207:8333:191662      163     7       140453055       60      76M     =       140453135       155     AAAATAGCCTCAATTCTTACCATCCACAAAATGGATCCAGACAACTGTTCAAACTGATGGGACCCACTCCATCGAG    8DDB??EDDBCAA@AFCB@EEBAFECFADDB@FGCBHFBGAEDEGDIA@FEFFFDHDBI8GCGA@AFDGECAH=CH    MD:Z:76 PG:Z:bwa.11     RG:Z:D0N3R.5    AM:i:37 NM:i:0  SM:i:37 MQ:i:60 OQ:Z:@C@
C0FJ4ACXX120306:2:2306:10861:141466     163     7       140453056       60      76M     =       140453131       150     AAATAGCCTCAATTCTTACCATCCACAAAATGGATCCAGACAACTGTTCAAACTGATGGGACCCACTCCATCGAGA    8CD@?EDDBEAC@AFDB@=CBAFDBECDDDAIDDBGFCICECDEEI@BGDEFEEJDCIIHDGGHCDEGFDCG@CHA    MD:Z:76 PG:Z:bwa.4      RG:Z:C0FJ4.2    AM:i:37 NM:i:0  SM:i:37 MQ:i:60 OQ:Z:@CC
C0FJ4ACXX120306:3:1101:11032:132783     163     7       140453057       60      76M     =       140453206       224     AATAGCCTCAATTCTTACCATCCACAAAATGGATCCAGACAACTGTTCAAACTGATGGGACCCACTCCATCGAGAT    7E??FDEBE@C@@FCA@EFB@GFCFCEEEAIHBAHGDICFDEGEIBCHCEFGEJDBIIIDFGGCHEIGBBHABGC@    MD:Z:76 PG:Z:bwa.19     RG:Z:C0FJ4.3    AM:i:37 NM:i:0  SM:i:37 MQ:i:60 OQ:Z:CC
D0N3RACXX120302:8:1308:12146:47510      83      7       140453057       60      76M     =       140452991       -141    AATAGCCTCAATTCTTACCATCCACAAAATGGATCCAGACAACTGTTCAAACTGATGGGACCCACTCCATCGAGAT    >A>AEGGCH@<@DHF<6FHB@DDAHBCB@CBE<CHIDGAICBGBEEBFBCAGAHBBGFDCEFG=GCFH@@AEB?@>    MD:Z:76 PG:Z:bwa.8      RG:Z:D0N3R.8    AM:i:37 NM:i:0  SM:i:37 MQ:i:60 OQ:Z:7EA=
D0N3RACXX120302:4:2202:7920:44567       83      7       140453062       60      76M     =       140453019       -118    CCTCAATTATTACCATCCACAAAATGGATCCAGGCAACTGTTCAAACTGATGGGACCCACTCCATCGAGATTTCAC    ><BBAB</.E==IHBCHGBHDDDCCGHADFFB5*ICBICFEDICCBHCHBCFFHAHFGAE>D3+C@GDF@EECFBA    MD:Z:8C24A42    PG:Z:bwa.14     RG:Z:D0N3R.4    AM:i:37 NM:i:2  SM:i:37 MQ:i:60 OQ:Z
D0N3RACXX120302:4:2207:9338:88566       83      7       140453063       60      76M     =       140453027       -111    CTCAATTCTTACCATCCACAAAATGGATCCAGACAACTGTTCAAACTGATGGGACCCACTCCATCGAGATTTCACT    @BCACDCHEA@IIBEHHCICDCCDGHBEIIEGBBCBGDGEDHCCAHCHBCFFFAGGE?HBGHBC@GDGADECGADA    MD:Z:76 PG:Z:bwa.14     RG:Z:D0N3R.4    AM:i:37 NM:i:0  SM:i:37 MQ:i:60 OQ:Z:=EEH
D0MUKACXX120302:7:2107:6342:182348      163     7       140453064       60      76M     =       140453194       205     TCAATTCTTACCATCCACAAAATGGATCCAGACAACTGTTCAAACTGATGGGACCCACTCCATCGAGATTTCACTG    8FBC??DB??DE@@FEBFBDDD@HGCAGGBFBFCEFDI@AHCEEFEIABIFHDFHGBEDIGCAHBCIBAABHBFBG    MD:Z:76 PG:Z:bwa.12     RG:Z:D0MUK.7    AM:i:37 NM:i:0  SM:i:37 MQ:i:60 OQ:Z:CCC
D0N3RACXX120302:6:2207:13161:42032      99      7       140453067       60      76M     =       140453150       158     ATTCTTACCATCCACAAAATGGATCCAGACAACTGTTCAAACTGATGGGACCCACTCCATCGAGATTTCACTGTAG    @>BFD@?CFB?CEBEBECEBGHCAEGBGCFEEFDGAAECEEGDGCAEF<DFGGCGDGGCBH>CG@=C>GFDCG>>B    MD:Z:76 PG:Z:bwa.3      RG:Z:D0N3R.6    AM:i:37 NM:i:0  SM:i:37 MQ:i:60 OQ:Z:@@CFF
D0MUKACXX120302:3:2105:4768:123149      147     7       140453067       60      76M     =       140453014       -128    ATTCTTACCATCCACAAAATGGATCCAGACAACTGTTCAAACTGATGGGACCCACTCCATCGAGATTTCACTGTAG    @CBED@@JHCDIHCHCCDCDGGCCHIFGBIDAHCEEDICBBJCGBBEEEAHH@AHCGH@A?ECE@CBAF?E@B@C8    MD:Z:76 PG:Z:bwa        RG:Z:D0MUK.3    AM:i:37 NM:i:0  SM:i:37 MQ:i:60 OQ:Z:CE?EC
C0FJ4ACXX120306:6:2205:6607:28512       1113    7       140453068       37      76M     =       140453068       0       TTCTTACCATCCACAAAATGGATCCAGACAACTGTTCAAACTGATGGGACCCACTCCATCGAGATTTCACTGTAGC    @?@A/>GGABGH@IEDDCDGGBCHFFGBHCCGCFEEHDDCGDGBCEFGCFEGBFCGGBDAFEGBEDCGAFCDADEB    MD:Z:76 PG:Z:bwa.18     RG:Z:C0FJ4.6    AM:i:0  NM:i:0  SM:i:37 OQ:Z:?=?=)7HIGAIGAE
```

**Comment by jakeakopp** [comment]
@jmarshall Thanks for putting this together!

**Pull request merged**
