### PR TITLE
note the effects of different compression libs

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by jmarshall** [comment]
This is not limited to libdeflate — different versions of system zlib (or different distro-specific patches to it) or running it on different platforms might well cause different compressed bytestreams too. How deterministic is zlib? Who knows. The conservative assumption is to assume it's not.

For most HTSlib users all this is irrelevant anyway. It's only people trying to compare compressed files e.g. in test suites who might need a small note about this.

**Comment by mr-c** [comment]
@jmarshall Feel free to add to the branch https://github.com/mr-c/htslib/invitations

**Comment by jkbonfield** [comment]
Even with the same deflate it's possible to alter the compression level programatically or eg via `samtools view -O bam,level=9`.  We've never stated the binary content matters and must be kept identical.

This is a storm in a teacup over a poorly conceived test.

**Comment by jmarshall** [comment]
Good point about level settings, and agreed about teacups. There would be some scope for adding something like the following to the README:

```
Many of these file formats and associated index formats are compressed, 
which in this implementation involves the use of system or external
compression libraries such as zlib.  Hence the exact bytes in compressed
files output by HTSlib may vary across different compression libraries or 
with different compression level settings, so tasks requiring byte-for-byte 
equivalence across repeated runs should compare decompressed file contents.
```

However I am in two minds about whether this would be useful information for the reproducible science crowd or would end up pointlessly scaring the horses…

**Comment by mr-c** [comment]
> teacups

FYI, not trying to make a storm, just trying to be helpful

> However I am in two minds about whether this would be useful information for the reproducible science crowd or would end up pointlessly scaring the horses…

+1 for a note from a reproducible science booster

@jmarshall I adopted your suggested wording and moved it to the end of the document

**Comment by jmarshall** [comment]
> I adopted your suggested wording and moved it to the end of the document

If the benefits of a note like this outweigh the downsides, the place for it would be README rather than INSTALL — as the latter is less likely to be read by end users and might not even be installed by binary packages. For example, some outfit named Debian don't install INSTALL, though actually they don't install the README either ([#922860](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=922860))…

**Comment by mr-c** [comment]
>  the place for it would be README rather than INSTALL

Done :-)

**Comment by jkbonfield** [comment]
We felt that this is likely to not help many people (to be frank I expect most people wouldn't read it anyway) and may cause more confusion given there are several formats supported by htslib which have differing ways to uncompress and perform comparisons.  Plus there are potential differences even with filenames encoded in some situations, or `@PG` headers.

Rather than muddy the waters further we decided to just omit this.  Sorry for that, but thanks for your time.

**Comment by mr-c** [comment]
> We've never stated the binary content matters and must be kept identical.

Can this be made explicit?

**Comment by jkbonfield** [comment]
What problem are you trying to address here exactly?

If we look at, e.g. the gzip man page it doesn't state that the output will be different if you use -1 to -9 because it's obvious.  Similarly you're not going to find warnings in e.g. evince, about the impact of linking against a newer zlib (eg CloudFlare's or Intel's) on the bit-exactness of any PDFs saved.

Even zlib itself has on occasion tweaked its algorithm to improve compression ratios (eg compare output from 1.1.0 with 1.2.0), which means compressed files differ - obviously.

**Comment by jmarshall** [comment]
> What problem are you trying to address here exactly?

Look back at the original commit:

> Note: turning on --with-libdeflate will cause any compressed output, such as Tabix indices, to have different bytes, though the underlying uncompressed data streams will be unchanged.

He's trying to prevent others from getting the same surprise that Debian got, when turning on libdeflate led to test failures in an unfortunately-written test suite. A laudable goal in itself, mired by: it's not just libdeflate / maybe it shouldn't be a surprise (or at best a “oh yeah; d'oh; move on”) / those in line to get this surprise are not the bulk of HTSlib users / any brief wording has the potential to be confusing.

**Comment by jkbonfield** [comment]
I remembered it being something to do with a poorly written test, but I'm sure this was actually mentioned at some point here.  It seems to have vanished since then and that original commit doesn't mention testing either.  I assume there was a link to an external issue at one point which has since been edited away.

Regardless, adding to the README file isn't going to fix those tests.  Nor is it likely to stop people making the same mistake again either.  More documentation isn't always good, especially in a README file.  People stop reading once it gets too long, so excess test reduces the impact of the rest of the file.

Anyway, decision has been made.  No change.

**Comment by jmarshall** [comment]
Nothing but agreement from me :smile:. It was #827 — contemporaneous, so the unstated link was obvious at the time.

**Pull request closed without merging**
